import json
import random
from pathlib import Path

PERSONAS = {
    "lenient_supportive": {
        "examples": [
            ("yo stream was fire last night!!", {"strikes": 0}),
            ("this is the best clutch i've seen all week", {"strikes": 0}),
            ("nice clutch, deserved that dub", {"strikes": 0}),
            ("poggers play, so clean", {"strikes": 0}),
            ("ggs everyone, fun lobby", {"strikes": 0}),
            ("love the vibe tonight", {"strikes": 0}),
            ("amazing gameplay as always", {"strikes": 0}),
            ("you're carrying hard tonight", {"strikes": 0}),
            ("that was insane, well played", {"strikes": 0}),
            ("best streamer on twitch fr", {"strikes": 0}),
            ("keep up the great content", {"strikes": 0}),
            ("subbed for a year, worth every penny", {"strikes": 0}),
            ("your content always makes my day", {"strikes": 0}),
            ("can't wait for the next stream", {"strikes": 0}),
            ("this is why i watch you", {"strikes": 0}),
            ("can i drop a link to my montage?", {"strikes": 0}),
            ("hey could you explain that strat again?", {"strikes": 0}),
            ("what settings do you use?", {"strikes": 0}),
            ("can we get a timeout on that spammer pls", {"strikes": 0}),
            ("when's the next tournament?", {"strikes": 0}),
            ("sorry if that was rude earlier, just hyped", {"strikes": 1}),
            ("sorry mods, didnt know link posting was banned", {"strikes": 1}),
            ("sorry for spamming earlier, won't happen again", {"strikes": 1}),
            ("my bad, didn't mean to be toxic", {"strikes": 1}),
            ("apologies for the earlier comment", {"strikes": 1}),
            ("stop talking and play dude boring", {"strikes": 1}),
            ("audio desync again, please fix", {"strikes": 0}),
            ("your mic is clipping bro, hurts my ears", {"strikes": 0}),
            ("mic too quiet, can you bump gain?", {"strikes": 0}),
            ("lagging a bit today?", {"strikes": 0}),
            ("bro said chat can't behave LUL", {"strikes": 0}),
            ("chat going wild tonight", {"strikes": 0}),
            ("yall are crazy in here", {"strikes": 0}),
            ("linking my discord for team finders: https://discord.gg/abc", {"strikes": 0}),
            ("check out my channel too", {"strikes": 0}),
        ],
    },
    "firm_professional": {
        "examples": [
            ("go kys lol", {"strikes": 2}),
            ("unban me coward, free speech!!", {"strikes": 3}),
            ("bro ur gameplay is trash uninstall", {"strikes": 2}),
            ("this game is trash you're trash chat is trash", {"strikes": 2}),
            ("you all suck get gud", {"strikes": 2}),
            ("ratio + didn't ask + cry more", {"strikes": 2}),
            ("you're washed up, retire already", {"strikes": 2}),
            ("worst streamer ever, kys", {"strikes": 3}),
            ("nobody likes you, quit streaming", {"strikes": 2}),
            ("ur mods are power hungry clowns", {"strikes": 1}),
            ("this stream is garbage", {"strikes": 2}),
            ("you're a fraud and a scammer", {"strikes": 2}),
            ("ban me idc this chat is toxic", {"strikes": 2}),
            ("you're so bad at this game", {"strikes": 2}),
            ("worst plays i've ever seen", {"strikes": 2}),
            ("follow me for free coins!!! http://spam.link", {"strikes": 1}),
            ("free followers at http://getfollows.biz", {"strikes": 2}),
            ("type !freecoins to win $$$", {"strikes": 2}),
            ("follow my insta for giveaways @fakeprize", {"strikes": 2}),
            ("click here for free vbucks: bit.ly/scam", {"strikes": 2}),
            ("get rich quick, visit my site", {"strikes": 2}),
            ("free money hack, dm me", {"strikes": 2}),
            ("promo code: SCAM2024", {"strikes": 1}),
            ("subscribe to my onlyfans", {"strikes": 2}),
            ("buy followers cheap, dm", {"strikes": 2}),
            ("why are mods sleeping this chat is wilding", {"strikes": 1}),
            ("mod u even on? this spam is crazy", {"strikes": 1}),
            ("mods asleep, bots posting links nonstop", {"strikes": 1}),
            ("this chat toxic af", {"strikes": 1}),
            ("you banned my friend for nothing, power trip", {"strikes": 1}),
            ("mods are useless here", {"strikes": 1}),
            ("why did you timeout me i just asked a question", {"strikes": 1}),
            ("mods on a power trip tonight", {"strikes": 1}),
            ("do a giveaway or i'm leaving", {"strikes": 1}),
            ("play my game request or i unsub", {"strikes": 1}),
            ("read my donation or i'm gone", {"strikes": 1}),
            ("answer my question now", {"strikes": 1}),
            ("bad word filter sucks i'll bypass it lmao", {"strikes": 2}),
            ("f*ck your rules", {"strikes": 2}),
            ("sh1t mods can't catch me", {"strikes": 2}),
            ("l3ts s33 if th3y c4n r34d th1s", {"strikes": 2}),
            ("you all are sheep following this streamer", {"strikes": 2}),
            ("this community is a cult", {"strikes": 2}),
            ("yall are simps", {"strikes": 1}),
            ("chat full of bots", {"strikes": 1}),
            ("keep politics out of chat", {"strikes": 0}),
            ("why are you talking about that topic", {"strikes": 1}),
        ],
    },
    "nuanced_patient": {
        "examples": [
            ("that's sus but maybe they meant it as a joke?", {"strikes": 0}),
            ("yall sensitive, that wasn't even toxic", {"strikes": 0}),
            ("seems harsh but i get why", {"strikes": 0}),
            ("could be sarcasm, hard to tell", {"strikes": 0}),
            ("maybe they're having a bad day", {"strikes": 0}),
            ("your mic is clipping bro, hurts my ears", {"strikes": 0}),
            ("audio desync again, please fix", {"strikes": 0}),
            ("mic too quiet, can you bump gain?", {"strikes": 0}),
            ("lagging a bit today?", {"strikes": 0}),
            ("fps drops during fights", {"strikes": 0}),
            ("can you turn down game volume?", {"strikes": 0}),
            ("overlay covering important info", {"strikes": 0}),
            ("hey could you explain that strat again?", {"strikes": 0}),
            ("what build are you running?", {"strikes": 0}),
            ("can we discuss that play?", {"strikes": 0}),
            ("why did you do that?", {"strikes": 0}),
            ("can you show your settings?", {"strikes": 0}),
            ("can we get a timeout on that spammer pls", {"strikes": 0}),
            ("please ban that slur user", {"strikes": 0}),
            ("can we keep politics out of chat?", {"strikes": 0}),
            ("maybe warn them first?", {"strikes": 0}),
            ("that user seems new, give them a chance", {"strikes": 0}),
            ("sorry, didn't realize that was against rules", {"strikes": 1}),
            ("my bad, i'll be more careful", {"strikes": 1}),
            ("didn't mean to offend anyone", {"strikes": 1}),
            ("i understand why that was removed", {"strikes": 1}),
            ("linking my discord for team finders: https://discord.gg/abc", {"strikes": 0}),
            ("can i share my montage link?", {"strikes": 0}),
            ("is self-promo allowed here?", {"strikes": 0}),
            ("what's the rule on links?", {"strikes": 0}),
            ("maybe try a different approach next time", {"strikes": 0}),
            ("that strategy didn't work, but good try", {"strikes": 0}),
            ("consider adjusting your sensitivity", {"strikes": 0}),
            ("love the stream but chat is wild tonight", {"strikes": 0}),
            ("great content, maybe slow down a bit", {"strikes": 0}),
            ("enjoying this but audio needs work", {"strikes": 0}),
        ],
    },
}

out = []
users = 0
for _ in range(400):
    persona = random.choice(list(PERSONAS.keys()))
    template = random.choice(PERSONAS[persona]["examples"])
    comment, meta = template
    users += 1
    sample = {
        "comment": comment,
        "meta": {"user": f"user_{users:03d}", "account_age_days": random.randint(10, 900), **meta},
        "persona": persona,
    }
    out.append(sample)

output_path = Path("data/synthetic_comments.json")
output_path.parent.mkdir(parents=True, exist_ok=True)
with output_path.open("w", encoding="utf-8") as f:
    json.dump(out, f, indent=2)
print(f"Wrote {len(out)} samples to {output_path}")

